### ISSUE TITLE
No longer working on Mac with XIV on Mac launcher?

### ISSUE THREAD

**Issue by moontarp** [0ceal0t/Dalamud-VFXEditor#113]
<img width="607" alt="Screenshot 2023-04-24 at 6 16 56 PM" src="https://user-images.githubusercontent.com/131776551/234278848-ba82f88f-b55e-4660-803a-679395ff45b4.png">

For the past month and a half or so VFXedit has failed to update or open for me with Dalamud. I have not found any other mac users interested in modding (no surprise there) who can confirm it's an issue just with XIV on Mac, but nothing I do seems to fix it, and the issue has persisted over several VFXedit updates and patches. It was working just fine in February.

**Comment by 0ceal0t** [comment]
can you check the `/xllog` command or `dalamud.log` file and see if there are any errors?

**Comment by moontarp** [comment]
Sure, I deleted the plugin and restarted the game to get it to pull up the install error upon reinstalling the plugin. Getting something about the function "normalize" not being defined. (Redacted my name in certain filepaths here.)

`09:51:57.582 | ERR [LOCALPLUGIN] Error while loading VFXEditor
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> SharpDX.CompilationException: Z:\Users\[NAME]\Library\Application Support\XIV on Mac\installedPlugins\VFXEditor\1.7.4.1\Shaders\ModelPreview.fx:31:15: E5005: Function "normalize" is not defined.
   at SharpDX.D3DCompiler.ShaderBytecode.Compile(IntPtr textSource, Int32 textSize, String entryPoint, String profile, ShaderFlags shaderFlags, EffectFlags effectFlags, ShaderMacro[] defines, Include include, String sourceFileName, SecondaryDataFlags secondaryDataFlags, DataStream secondaryData)
   at SharpDX.D3DCompiler.ShaderBytecode.Compile(String shaderSource, String entryPoint, String profile, ShaderFlags shaderFlags, EffectFlags effectFlags, ShaderMacro[] defines, Include include, String sourceFileName, SecondaryDataFlags secondaryDataFlags, DataStream secondaryData)
   at SharpDX.D3DCompiler.ShaderBytecode.CompileFromFile(String fileName, String entryPoint, String profile, ShaderFlags shaderFlags, EffectFlags effectFlags, ShaderMacro[] defines, Include include)
   at VfxEditor.DirectX.ModelPreview..ctor(Device device, DeviceContext ctx, String shaderPath) in /work/repo/VFXEditor/DirectX/ModelPreview.cs:line 65
   at VfxEditor.DirectX.DirectXManager..ctor() in /work/repo/VFXEditor/DirectX/DirectXManager.cs:line 18
   at VfxEditor.Plugin..ctor(DalamudPluginInterface pluginInterface, ClientState clientState, CommandManager commandManager, Framework framework, Condition condition, ObjectTable objects, SigScanner sigScanner, DataManager dataManager, TargetManager targetManager, KeyState keyState) in /work/repo/VFXEditor/Plugin.cs:line 126
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.InvokeWithManyArguments(RuntimeConstructorInfo ci, Int32 argCount, Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects) in C:\goatsoft\companysecrets\dalamud\IoC\Internal\ServiceContainer.cs:line 107
   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 422
09:51:57.589 | ERR [PLUGINW] Plugin installer threw an unexpected error
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> SharpDX.CompilationException: Z:\Users\[NAME]\Library\Application Support\XIV on Mac\installedPlugins\VFXEditor\1.7.4.1\Shaders\ModelPreview.fx:31:15: E5005: Function "normalize" is not defined.
   at SharpDX.D3DCompiler.ShaderBytecode.Compile(IntPtr textSource, Int32 textSize, String entryPoint, String profile, ShaderFlags shaderFlags, EffectFlags effectFlags, ShaderMacro[] defines, Include include, String sourceFileName, SecondaryDataFlags secondaryDataFlags, DataStream secondaryData)
   at SharpDX.D3DCompiler.ShaderBytecode.Compile(String shaderSource, String entryPoint, String profile, ShaderFlags shaderFlags, EffectFlags effectFlags, ShaderMacro[] defines, Include include, String sourceFileName, SecondaryDataFlags secondaryDataFlags, DataStream secondaryData)
   at SharpDX.D3DCompiler.ShaderBytecode.CompileFromFile(String fileName, String entryPoint, String profile, ShaderFlags shaderFlags, EffectFlags effectFlags, ShaderMacro[] defines, Include include)
   at VfxEditor.DirectX.ModelPreview..ctor(Device device, DeviceContext ctx, String shaderPath) in /work/repo/VFXEditor/DirectX/ModelPreview.cs:line 65
   at VfxEditor.DirectX.DirectXManager..ctor() in /work/repo/VFXEditor/DirectX/DirectXManager.cs:line 18
   at VfxEditor.Plugin..ctor(DalamudPluginInterface pluginInterface, ClientState clientState, CommandManager commandManager, Framework framework, Condition condition, ObjectTable objects, SigScanner sigScanner, DataManager dataManager, TargetManager targetManager, KeyState keyState) in /work/repo/VFXEditor/Plugin.cs:line 126
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.InvokeWithManyArguments(RuntimeConstructorInfo ci, Int32 argCount, Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects) in C:\goatsoft\companysecrets\dalamud\IoC\Internal\ServiceContainer.cs:line 107
   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 422
   at Dalamud.Plugin.Internal.PluginManager.LoadPluginAsync(FileInfo dllFile, LocalPluginManifest manifest, PluginLoadReason reason, Boolean isDev, Boolean isBoot, Boolean doNotLoad) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 883
   at Dalamud.Plugin.Internal.PluginManager.InstallPluginAsync(RemotePluginManifest repoManifest, Boolean useTesting, PluginLoadReason reason) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 830
{ } [ Send ]`

**Comment by moontarp** [comment]
Pleased to say it's just started working again, after two months of this error!
