### ISSUE TITLE
Exporting as textools

### ISSUE THREAD

**Issue by oxxtazxxo** [0ceal0t/Dalamud-VFXEditor#118]
Instead of saving as a TTMP, its saving as a textools temp? Its done this more than once. included image below
![explorer_lg7T061swM](https://user-images.githubusercontent.com/38712464/236026123-3ced7e14-3ccb-429b-8ac3-11270eb336e5.png)

**Comment by 0ceal0t** [comment]
can you check your `/xllog` and see if there are any errors?

**Comment by oxxtazxxo** [comment]
18:49:12.099 | ERR [VFXEditor] Could not export to TexTools
System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. : 'D:\TexTools\My Mods Made\Testing\Comms\Snap\sage - get shit on\Get Shit On <3.ttmp2'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.DoCreateFromDirectory(String sourceDirectoryName, String destinationArchiveFileName, Nullable`1 compressionLevel, Boolean includeBaseDirectory, Encoding entryNameEncoding)
   at VfxEditor.TexTools.TexToolsDialog.Export(String saveFile) in /work/repo/VFXEditor/Ui/TexTools/TexToolsDialog.cs:line 116
18:51:21.569 | ERR [VFXEditor] Could not export to Penumbra
System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. : 'D:\TexTools\My Mods Made\Testing\Comms\Snap\sage - get shit on\Get Shit On <3.pmp'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.DoCreateFromDirectory(String sourceDirectoryName, String destinationArchiveFileName, Nullable`1 compressionLevel, Boolean includeBaseDirectory, Encoding entryNameEncoding)
   at VfxEditor.Penumbra.PenumbraDialog.Export(String saveFile) in /work/repo/VFXEditor/Ui/Penumbra/PenumbraDialog.cs:line 103
{ } [ Send ]


Same thing for penumbra

**Comment by 0ceal0t** [comment]
try exporting it with a filename that doesn't have a `\` or `<3` in the name

**Comment by oxxtazxxo** [comment]
yeah i fixed it as soon as i saw that!

**Comment by 0ceal0t** [comment]
did that resolve the issue?

**Comment by oxxtazxxo** [comment]
it resolved the issue. is it a wording issue? is that why? i think before it didnt have that <3 either

**Comment by 0ceal0t** [comment]
yeah having special characters like `/` or `<` can mess up the file path
