### ISSUE TITLE
SCD Read Error

### ISSUE THREAD

**Issue by Kurochi51** [0ceal0t/Dalamud-VFXEditor#120]
I got this error whenever I tried to read an .scd created with ff14 voice pack creator.

```
2023-05-05 10:44:14.922 +03:00 [ERR] [VFXEditor] Error Reading File
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.ReadByte()
   at VfxEditor.Parsing.ParsedInt.Read(BinaryReader reader, Int32 size) in /work/repo/VFXEditor/Parsing/Int/ParsedInt.cs:line 25
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at VfxEditor.ScdFormat.ScdAttributeEntry.Read(BinaryReader reader) in /work/repo/VFXEditor/ScdFormat/Attribute/ScdAttributeEntry.cs:line 44
   at VfxEditor.ScdFormat.ScdEntry.Read(BinaryReader reader, Int32 offset) in /work/repo/VFXEditor/ScdFormat/Entries/ScdEntry.cs:line 14
   at VfxEditor.ScdFormat.ScdFile..ctor(BinaryReader reader, Boolean checkOriginal) in /work/repo/VFXEditor/ScdFormat/ScdFile.cs:line 61
   at VfxEditor.ScdFormat.ScdDocument.FileFromReader(BinaryReader reader) in /work/repo/VFXEditor/ScdFormat/ScdDocument.cs:line 14
   at VfxEditor.FileManager.FileManagerDocument`2.LoadLocal(String localPath) in /work/repo/VFXEditor/FileManager/FileManagerDocument.cs:line 90
```

**Comment by 0ceal0t** [comment]
sorry for the long response! Are you using a more recent version of the voice pack creator?

**Comment by Kurochi51** [comment]
I wasn't the creator of the file, so I'm unsure.
