### ISSUE TITLE
Game crash when replacing texture inside VFX

### ISSUE THREAD

**Issue by Kurochi51** [0ceal0t/Dalamud-VFXEditor#135]
I tried replacing one of the textures used in the A-D 1-4 markers, but the game crashes as soon as I select the DDS. Am I supposed to convert the DDS? The crash log and error:
```
2023-06-19 12:23:59.880 +03:00 [ERR] Failed to load image from raw data
SharpDX.SharpDXException: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.

   at ImGuiScene.RawDX11Scene.CreateTexture(Void* pixelData, Int32 width, Int32 height, Int32 bytesPerPixel) in D:\a\Dalamud\Dalamud\lib\ImGuiScene\ImGuiScene\RawDX11Scene.cs:line 257
   at Dalamud.Interface.Internal.InterfaceManager.LoadImageRaw(Byte[] imageData, Int32 width, Int32 height, Int32 numChannels) in C:\goatsoft\companysecrets\dalamud\Interface\Internal\InterfaceManager.cs:line 304
2023-06-19 12:23:59.887 +03:00 [FTL] Unhandled exception on AppDomain
System.InvalidOperationException: Load failed.
   at ImGuiFileDialog.FileDialog.<>c__DisplayClass67_0.<LoadTexturePreview>b__0() in /work/repo/VFXEditor/ImGuiFileDialog/FileDialog.Dialog.cs:line 501
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at ImGuiFileDialog.FileDialog.LoadTexturePreview(FileStruct file) in /work/repo/VFXEditor/ImGuiFileDialog/FileDialog.Dialog.cs:line 478
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```
![ffxiv_dx11_2023-06-19_12-24-23](https://github.com/0ceal0t/Dalamud-VFXEditor/assets/5596521/b8f87d67-a0ed-44c7-87eb-d6c799d1927d)

**Comment by 0ceal0t** [comment]
I'll look into what's causing the crash, but for now try disabling "File picker image preview" in `File > Settings`
